### ISSUE TITLE
Typescript interface issue

### ISSUE THREAD

**Issue by tyler7771** [react-cropper/react-cropper#170]
I may be doing something wrong here, but after upgrading to 2.0.0-0 I'm getting a typescript error.

` Property 'src' does not exist on type 'IntrinsicAttributes & ReactCropperProps & { children?: ReactNode; }'.`

I get the same issue when I delete src with style. Am I doing something wrong or is there an issue with the interface?

```javascript
return (
    <Cropper
        guides={false}
        src={this.state.imageUrl}
        style={{ height: "100%", width: "100%" }}
        zoomOnWheel={false}
        autoCropArea={0.75}
        viewMode={1}
        onInitialized={(instance: Cropper) => this.setInstance(instance)}
    />
);
```

**Comment by shekhar-shubhendu** [comment]
check this sandbox
https://codesandbox.io/s/react-cropper-demo-j2mbz?file=/src/Demo.tsx

**Comment by tyler7771** [comment]
I updated my version of typescript and it fixed this issue. Updating to 2.0.0-0 didn't fix the issue I was having before updating.

**Comment by shekhar-shubhendu** [comment]
@tyler7771 can please provide the details of the issues you were having earlier or are still facing after updating to 2.0.0-0 and I'll try to see if I can be of any help.
if it is something related to react-cropper then maybe I can add it to the final version.

> I updated my version of typescript and it fixed this issue. Updating to 2.0.0-0 didn't fix the issue I was having before updating.
