### ISSUE TITLE
Typescript error for every prop used in Cropper component

### ISSUE THREAD

**Issue by korneSt** [react-cropper/react-cropper#521]
**Describe the bug**
I'm getting this error for every prop that I use in Cropper component.

```
Type '{ key: ImageType; src: string; ref: any; style: { maxWidth: string; display: string; margin: string; maxHeight: string; minHeight: string; }; autoCrop: boolean; minContainerWidth: number; ... 12 more ...; cropstart: () => void; }'
 is not assignable to type 'IntrinsicAttributes & ReactCropperProps & RefAttributes<HTMLImageElement>'.
Property 'autoCrop' does not exist on type 'IntrinsicAttributes & ReactCropperProps & RefAttributes<HTMLImageElement>'
```

**To Reproduce**
It was working fine on 2.1.4, after updating to 2.1.5 it breaks.

**Comment by Hummel37** [comment]
With the version v2.1.6-0 this works again.

**Comment by shekhar-shubhendu** [comment]
@korneSt  I was unable to repro this with 2.1.5 and it was mentioned that this got resolved automatically in newer version but if you face this again then please fork this sandbox and repro the issue
https://codesandbox.io/s/react-cropper-demo-forked-80lfb

**Comment by shekhar-shubhendu** [comment]
Closing for housekeeping purposes. Let me know if this needs more attention.
