### ISSUE TITLE
getting "Uncaught TypeError: _this.refs.cropper.getCroppedCanvas is not a function" while trying to save croped image.

### ISSUE THREAD

**Issue by dilipjoshis** [react-cropper/react-cropper#950]
This issue started occourring after upgrading my react version from 16 to 17
my code is as shown below:         
 <Cropper
            ref="cropper"
            src={this.state.selectedImage.file}
            style={{ height: 400, width: '100%' }}
            aspectRatio={1 / 1}
            guides={false}
          />

  saveProfilePicture = () => {
    this.refs.cropper.getCroppedCanvas().toBlob(this.blobbedImage, 'image/jpeg', 0.75);
  }

**Comment by rob-murray** [comment]
I don't think you can use string refs anymore.

https://codesandbox.io/s/amazing-sea-zo13qk?file=/src/App.js
